# Generated by Django 3.0.5 on 2020-04-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200427_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug_url',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
