# Generated by Django 3.0.5 on 2020-04-27 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
